### ISSUE TITLE
Using supportFinishAfterTransition instead of finish

### ISSUE THREAD

**Issue by TinasheMzondiwa** [klinker24/Android-DragDismissActivity#2]
I have a shared element transition going into the DragDismissActivity.
My view does not transition back because you're using finish() in
```
            @Override
            public void onDragDismissed() {
                super.onDragDismissed();
                activity.finish();
            }
 ```
Would it be possible to use `activity.supportFinishAfterTransition()` instead?
Or is there a change I can do on my side?

Thanks!

**Comment by klinker24** [comment]
Sure, does this work for you?

Commit: https://github.com/klinker24/Android-DragDismissActivity/commit/af462327039c496f57a80761dd8a563088a2484f

**Comment by TinasheMzondiwa** [comment]
Perfect!
Thanks a lot man.

**Comment by klinker24** [comment]
No problem, I will merge and push out an update later today for it
