### ISSUE TITLE
Library does not work with soft input

### ISSUE THREAD

**Issue by chennemann** [klinker24/Android-DragDismissActivity#5]
Normally if you display the keyboard an screen the View should be resized to reflect the ui size change. This is necessary to make all parts of the UI accessible for the user at all times.
Currently the Activity is not resized weather the keyboard is shown or not.

Do you know a way to get around this constraint?

**Comment by klinker24** [comment]
Can you fork and make an example so that I can play around with this and see what I can do?

**Comment by chennemann** [comment]
I hope the provided samples explains the issue

**Comment by klinker24** [comment]
Thanks, looks good. I will take a look when I get a few minutes

**Comment by klinker24** [comment]
Fixed with this: https://github.com/klinker24/Android-DragDismissActivity/commit/fa39e39560f382e4fbb4c4f48dad46d7e6233e4c

I will deploy `1.4.4` shortly and this change will be available.
